"""GET /api/v1/voice/personas and GET /api/v1/voice/manifest (P29 S3).

Read-only, cached, no auth change, no new table — purely additive alongside
the existing app/api/v1 routers. Read-only consumer of data generated by
scripts/gen_voice_clips.py (S2); never touches app/analysis, app/inference,
or app/api/v1/ws_inference.py.

Deliberately has NO `from __future__ import annotations` at module scope —
see the P27 incident (slowapi's `@limiter.limit` breaks app startup on the
prod image when the decorated module uses postponed annotations). This
router doesn't rate-limit today, but every other app/api/v1 router follows
the same no-future-annotations convention so that adding a limiter later
never reintroduces that bug here.
"""

import json
from functools import lru_cache
from pathlib import Path
from typing import Literal

import structlog
from fastapi import APIRouter, HTTPException, Response, status
from pydantic import BaseModel, Field

from app.voice.manifest_schema import MANIFEST_SCHEMA_VERSION
from app.voice.personas import PERSONA_KEYS, PERSONAS, PersonaKey

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/api/v1/voice", tags=["voice"])

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
MANIFEST_PATH = REPO_ROOT / "frontend" / "public" / "voice" / "manifest.json"

# The manifest changes only on a deliberate clip regeneration + redeploy —
# mirrors app/api/v1/model_assets.py's Cache-Control convention so clients
# don't refetch this on every page load.
_CACHE_CONTROL = "public, max-age=86400"


class PersonaOut(BaseModel):
    """Public persona metadata.

    Deliberately excludes ``prompt_fragment`` (an internal RAG system-prompt
    fragment, S7 — not something a client needs) and any voice id
    (provider-internal, resolved only by scripts/gen_voice_clips.py via
    data/voice/voice_ids.yaml).
    """

    key: PersonaKey
    name: str
    tone: str
    voice_texture: str


class ManifestEntry(BaseModel):
    """One clip's entry in frontend/public/voice/manifest.json's ``clips`` map."""

    file: str
    hash: str
    dur_ms: int


class ManifestPayload(BaseModel):
    """Top-level shape of frontend/public/voice/manifest.json (P29 S8).

    ``clips``: cue-key (``{persona}.{fault_id}``) -> audio metadata (S2).
    ``faults``: ``"{exercise}::{cue_text}"`` -> fault_id (S8) — the S1
    ``app.voice.fault_taxonomy.CUE_TEXT_LOOKUP`` table, folded into this
    already-fetched-and-cached manifest instead of a second route or a
    second static asset (S8 decision — see the P29 spec doc's S8 notes).
    ``version``: see ``app.voice.manifest_schema`` for what bumps it and why.
    """

    version: int
    clips: dict[str, ManifestEntry]
    faults: dict[str, str] = Field(default_factory=dict)


@lru_cache(maxsize=1)
def _load_manifest() -> ManifestPayload:
    """Read and parse manifest.json once per process.

    The manifest is regenerated only by a dev-time run of
    scripts/gen_voice_clips.py followed by a redeploy, so process-lifetime
    caching is correct. Callers must not mutate the returned object; tests
    that swap the file call ``_load_manifest.cache_clear()`` first.
    """
    with MANIFEST_PATH.open(encoding="utf-8") as f:
        raw: dict[str, object] = json.load(f)
    payload = ManifestPayload.model_validate(raw)
    if payload.version != MANIFEST_SCHEMA_VERSION:
        # Ops signal, not a hard failure: the committed manifest wasn't
        # regenerated after a schema bump. Distinct from (and orthogonal to)
        # the frontend's own stale-HTTP-cache check on the same field.
        logger.warning(
            "voice_manifest_version_mismatch",
            on_disk=payload.version,
            expected=MANIFEST_SCHEMA_VERSION,
        )
    return payload


@router.get("/personas", response_model=list[PersonaOut])
async def list_personas(response: Response) -> list[PersonaOut]:
    """The three coaching personas (ATLAS/FORGE/VECTOR) — static, no DB."""
    response.headers["Cache-Control"] = _CACHE_CONTROL
    return [
        PersonaOut(key=persona.key, name=persona.name, tone=persona.tone, voice_texture=persona.voice_texture)
        for persona in (PERSONAS[key] for key in PERSONA_KEYS)
    ]


@router.get("/manifest", response_model=ManifestPayload)
async def get_manifest(response: Response) -> ManifestPayload:
    """The {version, clips, faults} manifest scripts/gen_voice_clips.py emits.

    404s rather than 500s when the manifest hasn't been generated yet (a
    fresh checkout before S2, or a stripped test environment) — mirrors
    app/api/v1/model_assets.py's missing-file handling.
    """
    if not MANIFEST_PATH.is_file():
        logger.error("voice_manifest_missing", path=str(MANIFEST_PATH))
        raise HTTPException(status_code=404, detail="voice manifest not found")
    response.headers["Cache-Control"] = _CACHE_CONTROL
    return _load_manifest()


# ---------------------------------------------------------------------------
# Cue telemetry (P29 S7) — thesis metrics §11: cue latency (p95 < 400ms),
# cues per set, suppression rate. The arbiter (cueArbiter.ts) and the
# playback core (playbackManager.ts) run entirely client-side, so this is the
# one place they can reach structlog. No DB, no auth — a fire-and-forget beacon
# logged for aggregate analysis, never persisted per-user. Cue events carry
# fault id, severity, persona and timing only — no user content, no PII
# beyond that (spec §11 "Privacy").
# ---------------------------------------------------------------------------

Severity = Literal["high", "medium", "low", "milestone"]
CueEventKind = Literal["fired", "suppressed"]


class VoiceCueEvent(BaseModel):
    """One cue-arbiter decision, reported by `useCoachVoice`/`cueArbiter`.

    ``latency_ms`` (rep-boundary -> audio start, spec §11) is only meaningful
    for a ``fired`` event; a ``suppressed`` event never played anything, so
    it carries ``reason`` instead.
    """

    event: CueEventKind
    fault_id: str = Field(min_length=1, max_length=128)
    persona: PersonaKey | None = None
    severity: Severity | None = None
    reason: str | None = Field(default=None, max_length=64)
    latency_ms: float | None = Field(default=None, ge=0)


class VoiceCueEventBatch(BaseModel):
    """Request body for `POST /api/v1/voice/events` — a small batch, not a stream."""

    events: list[VoiceCueEvent] = Field(min_length=1, max_length=50)


@router.post("/events", status_code=status.HTTP_204_NO_CONTENT)
async def record_cue_events(batch: VoiceCueEventBatch) -> Response:
    """Log each cue-arbiter decision as a structlog event (spec §11 metrics).

    Emits exactly the three event names the thesis pipeline greps for:
    ``voice_cue_fired``, ``voice_cue_suppressed``, and (only when a fired
    event carries one) ``voice_cue_latency_ms``. Never raises on a
    malformed *value* within an otherwise-valid event — a lost beacon is a
    missed data point, never a reason to break the coaching session that
    sent it.
    """
    for event in batch.events:
        if event.event == "fired":
            logger.info(
                "voice_cue_fired",
                fault_id=event.fault_id,
                severity=event.severity,
                persona=event.persona,
            )
            if event.latency_ms is not None:
                logger.info(
                    "voice_cue_latency_ms",
                    fault_id=event.fault_id,
                    value=event.latency_ms,
                )
        else:
            logger.info(
                "voice_cue_suppressed",
                fault_id=event.fault_id,
                reason=event.reason,
                persona=event.persona,
            )
    return Response(status_code=status.HTTP_204_NO_CONTENT)
