"""GET /api/v1/voice/personas and GET /api/v1/voice/manifest (P29 S3).

Read-only, cached, no auth change, no new table — purely additive alongside
the existing app/api/v1 routers. Read-only consumer of data generated by
scripts/gen_voice_clips.py (S2); never touches app/analysis, app/inference,
or app/api/v1/ws_inference.py.

Deliberately has NO `from __future__ import annotations` at module scope —
see the P27 incident (slowapi's `@limiter.limit` breaks app startup on the
prod image when the decorated module uses postponed annotations). This
router doesn't rate-limit today, but every other app/api/v1 router follows
the same no-future-annotations convention so that adding a limiter later
never reintroduces that bug here.
"""

import json
from functools import lru_cache
from pathlib import Path

import structlog
from fastapi import APIRouter, HTTPException, Response
from pydantic import BaseModel

from app.voice.personas import PERSONA_KEYS, PERSONAS, PersonaKey

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/api/v1/voice", tags=["voice"])

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
MANIFEST_PATH = REPO_ROOT / "frontend" / "public" / "voice" / "manifest.json"

# The manifest changes only on a deliberate clip regeneration + redeploy —
# mirrors app/api/v1/model_assets.py's Cache-Control convention so clients
# don't refetch this on every page load.
_CACHE_CONTROL = "public, max-age=86400"


class PersonaOut(BaseModel):
    """Public persona metadata.

    Deliberately excludes ``prompt_fragment`` (an internal RAG system-prompt
    fragment, S7 — not something a client needs) and any voice id
    (provider-internal, resolved only by scripts/gen_voice_clips.py via
    data/voice/voice_ids.yaml).
    """

    key: PersonaKey
    name: str
    tone: str
    voice_texture: str


class ManifestEntry(BaseModel):
    """One clip's entry in frontend/public/voice/manifest.json."""

    file: str
    hash: str
    dur_ms: int


@lru_cache(maxsize=1)
def _load_manifest() -> dict[str, ManifestEntry]:
    """Read and parse manifest.json once per process.

    The manifest is regenerated only by a dev-time run of
    scripts/gen_voice_clips.py followed by a redeploy, so process-lifetime
    caching is correct. Callers must not mutate the returned dict; tests
    that swap the file call ``_load_manifest.cache_clear()`` first.
    """
    with MANIFEST_PATH.open(encoding="utf-8") as f:
        raw: dict[str, dict[str, object]] = json.load(f)
    return {key: ManifestEntry.model_validate(value) for key, value in raw.items()}


@router.get("/personas", response_model=list[PersonaOut])
async def list_personas(response: Response) -> list[PersonaOut]:
    """The three coaching personas (ATLAS/FORGE/VECTOR) — static, no DB."""
    response.headers["Cache-Control"] = _CACHE_CONTROL
    return [
        PersonaOut(key=persona.key, name=persona.name, tone=persona.tone, voice_texture=persona.voice_texture)
        for persona in (PERSONAS[key] for key in PERSONA_KEYS)
    ]


@router.get("/manifest", response_model=dict[str, ManifestEntry])
async def get_manifest(response: Response) -> dict[str, ManifestEntry]:
    """The cue-key -> {file, hash, dur_ms} manifest scripts/gen_voice_clips.py emits.

    404s rather than 500s when the manifest hasn't been generated yet (a
    fresh checkout before S2, or a stripped test environment) — mirrors
    app/api/v1/model_assets.py's missing-file handling.
    """
    if not MANIFEST_PATH.is_file():
        logger.error("voice_manifest_missing", path=str(MANIFEST_PATH))
        raise HTTPException(status_code=404, detail="voice manifest not found")
    response.headers["Cache-Control"] = _CACHE_CONTROL
    return _load_manifest()
